### ISSUE TITLE
Inclusion into F-Droid

### ISSUE THREAD

**Issue by ghost** [TTTDevs/NextCloudBookmarksAndroid#1]
F-Droid is an app repository ("store") that only serves free/libre/open-source apps. We received a packaging request at https://gitlab.com/fdroid/rfp/issues/107 and a working on this right now. If you object the inclusion, please let us know and i will remove it asap.

**Comment by mdev88** [comment]
Not at all, I was planning to do it myself, I just haven't had the time yet.
I will generate a release and add the link to f-droid when it's available.
