### ISSUE TITLE
White screen after "Sharing"

### ISSUE THREAD

**Issue by Scumi** [TTTDevs/NextCloudBookmarksAndroid#2]
After setting up my server URL, I tried to share a bookmark to the app. 
At first a screen opens and shows "Contacting Nextcloud, [...]".
Then the next screen opens, but this one is only white. I waited quite bit, but nothing happens there.

Other Nextcloud android apps work fine.

**Comment by mdev88** [comment]
A few things you might check:
- Double check the server's url, including http/https without a / at the end. For example: https://nextcloud.mydomain.com
- Make sure you have activated the Nextcloud Bookmarks app in you Nextcloud server.

In the future I will add more checks to the URL and more feedback when errors occur to help debug problems like this.

**Comment by budbay** [comment]
I am also seeing this issue.  URL is correct. I use a self signed certificate, I wonder if this is the issue.  Does this app support self signed certs?

**Comment by Scumi** [comment]
When I tried "http" instead of "https", I got a bit further. I think the app does not allow own certificates. 

Now (with http://...) it is "net::ERR_TOO_MANY_REDIRECTS", with apparently the correct path displayed.

**Comment by mdev88** [comment]
@Scumi the too many redirects error looks like an nginx/apache error message from your server, not from the app. I've seen that error message popup when the server is configured to force all traffic via https and you are trying to access it from http and there's some redirect loop going on. Try to access the same url from your mobile browser and you should have a similar result.

This is a webapp, it is basically a web browser frame with the same functionallity a browser has. It doesn't deal with certificates in any special way, but maybe the thing with the self-signed certificate needs to be handled differently... @budbay do you also have a self-signed certificate in your nextcloud server?

**Comment by budbay** [comment]
@martinchodev yes I am using self signed certs.

**Comment by mdev88** [comment]
Ok, so there's the issue. I will take a look on how to handle that in the next release.
Thanks for the feedback!

**Comment by budbay** [comment]
Sounds good, thanks. Look forward to trying the app.

**Comment by mdev88** [comment]
I have added some code to handle some possible errors from certificates, but I have no way of verifying it works at the moment. 
I have uploaded a new APK with these changes on a folder called "Test APK" in the root of the repository. Please try it and let me know if it works so I include these changes into the next release.

**Comment by budbay** [comment]
OK so its a little closer now, but still have issue.  I am now prompted on the slash screen with warning about cert.  I click on continue but it stays stuck on the splash screen "contacting next cloud" and does not go any further.

**Comment by mdev88** [comment]
Ok, I'll have to set myself a self-signed cert on some url and do further tests myself, but I think I'll be able to find a workaround.

**Comment by budbay** [comment]
Sounds good, let me know if you need further testing.

**Comment by mdev88** [comment]
I have updated the Test APK so that it only warns about the self-signed certificate but takes no aditional action, it just proceeds normally.
Please try the new APK and let me know if there is a change.

**Comment by budbay** [comment]
Just tried the new test.apk, I get a toast warning about self signed cert but same behavior as before, it hangs on splash screen without going any further.

**Comment by mdev88** [comment]
Can anyone give me the URL of a Nextcloud server where you have this problem so that I can try to reproduce this error?
Thanks

**Comment by mdev88** [comment]
This app is no longer under any kind of development
