### ISSUE TITLE
Session expires after X amount of time/hours/days

### ISSUE THREAD

**Issue by mdev88** [TTTDevs/NextCloudBookmarksAndroid#3]
I'm not sure if this is something that can be fixed... 
Maybe expiration time is defined by the server and just preserving the cookies inside the app might not be enough. If that is the case, users would need to re-login each time time the session expires 😢

**Comment by allan-null** [comment]
Hi! Your app is pretty cool, but I am sorry to say it goes against the way Nextcloud is supposed to work with third party apps: the user must login using an app password.
To make that happen, your app must make a HTTP request sending user and password in the authorisation header, and in the POST parameters you set the url and title for the bookmark. I believe you can still use webview but it would be a bit wonky, so I'd recommend you to send the HTTP requests direct from your app. Here is an example of an request sent to Nextcloud Bookmarks using JavaScript: https://github.com/marcelklehr/floccus/blob/master/src/lib/adapter-nextcloud.js#L14. Of course you also need to store user and password.

**Comment by mdev88** [comment]
This app is no longer in development
